tags:: python, upload
public:: true

- Ollama OCR Text:
- Error processing image: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/generate (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1440930e0>: Failed to establish a new connection: [Errno 61] Connection refused'))
- ![f'./assets/scans/2025-02-17_14-32-12-916238.jpg'](./assets/scans/2025-02-17_14-32-12-916238.jpg)
- - No markers detected.